FROM rocker/tidyverse:4.4.1

# Set global R options
RUN echo "options(repos = 'https://cloud.r-project.org')" > $(R --no-echo --no-save -e "cat(Sys.getenv('R_HOME'))")/etc/Rprofile.site
ENV RETICULATE_MINICONDA_ENABLED=FALSE

# Install Seurat's system dependencies
RUN apt-get update && \
    apt-get install -y \
    libhdf5-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    libpng-dev \
    libboost-all-dev \
    libxml2-dev \
    openjdk-8-jdk \
    python3-dev \
    python3-pip \
    wget \
    git \
    libfftw3-dev \
    libgsl-dev \
    libfreetype6-dev \
    libtiff5-dev \
    libjpeg-dev \
    build-essential \
    libfontconfig1-dev \
    libbz2-dev \
    liblzma-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    libcairo2-dev \
    llvm && \
    apt-get clean

# Install UMAP and other Python dependencies
RUN LLVM_CONFIG=/usr/lib/llvm/bin/llvm-config pip3 install llvmlite
RUN pip3 install numpy umap-learn scanpy

# Install FIt-SNE
RUN git clone --branch v1.2.1 https://github.com/KlugerLab/FIt-SNE.git && \
    g++ -std=c++11 -O3 FIt-SNE/src/sptree.cpp FIt-SNE/src/tsne.cpp FIt-SNE/src/nbodyfft.cpp  -o bin/fast_tsne -pthread -lfftw3 -lm

# Install Bioconductor dependencies
RUN R --no-echo --no-restore --no-save -e "install.packages('BiocManager')" && \
    R --no-echo --no-restore --no-save -e "BiocManager::install(c('multtest', 'S4Vectors', 'SummarizedExperiment', 'SingleCellExperiment', 'MAST', 'DESeq2', 'BiocGenerics', 'GenomicRanges', 'IRanges', 'rtracklayer', 'monocle', 'Biobase', 'limma', 'glmGamPoi'))"

# Install CRAN packages
RUN R --no-echo --no-restore --no-save -e "install.packages(c('VGAM', 'R.utils', 'metap', 'Rfast2', 'ape', 'enrichR', 'mixtools', 'tidyverse', 'spatstat.explore', 'spatstat.geom', 'hdf5r', 'Matrix'))"

# Install the latest version of Seurat (v5 or above) and other R packages
RUN R --no-echo --no-restore --no-save -e "install.packages(c('remotes', 'devtools'))" && \
    R --no-echo --no-restore --no-save -e "remotes::install_github('satijalab/seurat', upgrade = 'always')" && \
    R --no-echo --no-restore --no-save -e "remotes::install_github('mojaveazure/seurat-disk')" && \
    R --no-echo --no-restore --no-save -e "devtools::install_github('satijalab/seurat-data')" && \
    R --no-echo --no-restore --no-save -e "remotes::install_github('immunogenomics/harmony')" && \
    R --no-echo --no-restore --no-save -e "remotes::install_github('immunogenomics/symphony')"

# Install TFBSTools and update Azimuth
RUN R --no-echo --no-restore --no-save -e "BiocManager::install('TFBSTools')" && \
    R --no-echo --no-restore --no-save -e "update.packages(oldPkgs = c('withr', 'rlang'))" && \
    R --no-echo --no-restore --no-save -e "remotes::install_github('satijalab/seurat-data', 'seurat5')" && \
    R --no-echo --no-restore --no-save -e "remotes::install_github('satijalab/azimuth', 'master')"

# Copy your local files to the container
COPY ./ /screfmapping/
COPY ./data/cache_symphony_sct.uwot /home/rstudio/autoimmune_10x/

# Download and extract example data
RUN wget https://cf.10xgenomics.com/samples/cell/pbmc3k/pbmc3k_filtered_gene_bc_matrices.tar.gz && \
    tar xvf pbmc3k_filtered_gene_bc_matrices.tar.gz

# Set the working directory
WORKDIR /home/rstudio/autoimmune_10x

# Define the default command (you can modify or uncomment it based on your needs)
# CMD [ "R" ]